#include<iostream>
using namespace std;
#include<bits/stdc++.h>

/* Q. Best Time to Buy and Sell Stock -> variation = 1 transaction only

You are given an array prices where prices[i] is the price of a given stock on the ith day.
You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.

Return the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return 0.

Input: prices = [7,1,5,3,6,4]
Output: 5
Explanation: Buy on day 2 (price = 1) and sell on day 5 (price = 6), profit = 6-1 = 5.
Note that buying on day 2 and selling on day 1 is not allowed because you must buy before you sell.

Input: prices = [7,6,4,3,1]
Output: 0
Explanation: In this case, no transactions are done and the max profit = 0.

Intuition: 
Previous smaller of every buy day
If you are selling on ith day, you buy on the minimum price from 1st day to i-1 day

7, 1, 5, 3, 6, 4
0, 0, 1, 1, 1, 1

6-1 = 5 (ans)

We need to find the maximum profit. In order to maximize the profit, we need to buy the stock at its lowest price and sell it when the price is highest. In the given example the lowest price(1) is on Day 1 and the highest price is (7) is on Day 0. But we need to buy the stock before selling it therefore we need to modify this approach.

We can try to sell the stock every day and try to find the maximum profit that can be generated by selling the stock on that day. At last, we can return the maximum of these individual maximum profits as our answer. 

To find the individual maximum profit on a day ‘i’, we know the selling price, i.e the price of the stock on day i, we need to find the buying price. To maximize the profit on day ‘i’, the buying price should be the lowest price of the stock from day 0 to day i (see the graph above). This way we can keep track of the correct buying price for any day.

Follow up -> return day of  - [buy, sell, profit]
*/

int maxProfit(vector<int>& prices) {
    int n=prices.size();
    int mini=prices[0];
    int profit=0;
    int buyIndex=-1, sellIndex=-1;
    for(int i=1;i<n;i++){
        int curProfit = prices[i] - mini;

        if(curProfit > profit){
            profit = curProfit;
            sellIndex=prices[i];
        }

        if(prices[i] < mini){
            mini=prices[i];
            buyIndex=mini;
        }
    }
    cout<<"buy: "<<buyIndex<<" sell: "<<sellIndex<<" profit: "<<profit<<endl;
    return profit;
}

int main(){
    vector<int>prices={12,5,15,22};
    cout<<maxProfit(prices)<<endl;
}